project_id = "wvhigrqmhgoozbhhoqjg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
external_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.shipments]
verify_jwt = true

[functions.fleet-management]
verify_jwt = true

[functions.tracking]
verify_jwt = true

[functions.pricing-engine]
verify_jwt = false

[functions.notifications]
verify_jwt = true

[functions.admin-panel]
verify_jwt = true

[functions.drivers]
verify_jwt = true

[functions.customers]
verify_jwt = true

[functions.route-optimization]
verify_jwt = true

[functions.service-quotes]
verify_jwt = true

[functions.proof-of-delivery]
verify_jwt = true

[functions.issues]
verify_jwt = true

[functions.messages]
verify_jwt = true

[functions.drivers]
verify_jwt = true

[functions.customers]
verify_jwt = true

[functions.route-optimization]
verify_jwt = true

[functions.service-quotes]
verify_jwt = true